version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql:${MYSQL_VERSION:-latest}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-currency_calculator}
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_HOST: ${MYSQL_HOST:-127.0.0.1}
      MYSQL_PORT: ${MYSQL_PORT:-3306}
    volumes:
      - database_data:/var/lib/mysql:rw
  ###< doctrine/doctrine-bundle ###

  webserver:
    image: nginx:${NGINX_VERSION:-1.21}-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html:rw

  php:
    image: php:${PHP_VERSION:-8.2}-fpm
    volumes:
      - ./:/var/www/html:rw
    depends_on:
      - database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - database
    ports:
      - "8080:80"
    environment:
      PMA_HOST: ${MYSQL_HOST:-127.0.0.1}
      PMA_PORT: ${MYSQL_PORT:-3306}

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI port

  redis:
    image: redis:latest

volumes:
  database_data:
