controllers:
    resource: ../src/Controller/
    type: attribute

app_currency:
    resource: ../src/Controller/CurrencyController.php
    type: annotation

app_react:
    path: /crud
    controller: App\Controller\CurrencyController.php    